# # Experiment 10
## Exploring basics of NumPy Methods
### a) Create numpy arrays using various methods

In [2]:
# import numpy
import numpy as np

In [11]:
# create numpy array using array()
arr1 = np.array([5, 10, 15, 20, 25])
print(type(arr1))
print(len(arr1))
print(arr1)

<class 'numpy.ndarray'>
5
[ 5 10 15 20 25]


In [12]:
# create numpy array using linspace()
# linspace(start, stop, n)
arr2 = np.linspace(5, 15, 6)
print(len(arr2))
print(arr2)

6
[ 5.  7.  9. 11. 13. 15.]


In [15]:
# create numpy array using logspace()
# logspace(start, stop, n)
arr3 = np.logspace(2, 0, 2)
print(len(arr3))
print(arr3)

2
[100.   1.]


In [17]:
# create numpy array using arange()
# arange(start, stop, stepsize)
arr4 = np.arange(3, 33, 3)
print(len(arr4))
print(arr4)

10
[ 3  6  9 12 15 18 21 24 27 30]


In [18]:
# create numpy arrays using zeros() and ones()
arr5 = np.zeros(4)
print(arr5)

arr6 = np.zeros(4, float)
print(arr6)

arr7 = np.zeros(4, int)
print(arr7)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0 0 0 0]


In [19]:
arr5 = np.ones(4)
print(arr5)

arr6 = np.ones(4, float)
print(arr6)

arr7 = np.ones(4, int)
print(arr7)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1 1 1 1]


### b) Find sum, min, max, mean, median, stddev of numpy array

In [20]:
import numpy as np

# create numpy array
int_arr = np.arange(0, 200, 5)
print(int_arr)

print("Sum: ", np.sum(int_arr))
print("Min: ", np.min(int_arr))
print("Max: ", np.max(int_arr))
print("Mean: ", np.mean(int_arr))
print("Median: ", np.median(int_arr))
print("Standard deviation: ", np.std(int_arr))

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195]
Sum:  3900
Min:  0
Max:  195
Mean:  97.5
Median:  97.5
Standard deviation:  57.716981903075975


In [23]:
float_arr = np.array([2.02, 2.13, 2.14, 2.00, 1.99])
print(float_arr)

print("Sum: ", np.sum(float_arr))
print("Min: ", np.min(float_arr))
print("Max: ", np.max(float_arr))
print("Mean: ", np.mean(float_arr))
print("Median: ", np.median(float_arr))
print("Standard deviation: ", np.std(float_arr))

[2.02 2.13 2.14 2.   1.99]
Sum:  10.280000000000001
Min:  1.99
Max:  2.14
Mean:  2.056
Median:  2.02
Standard deviation:  0.06529931086925804
