# # Experiment 11
## NumPy Array objects
### a) Program comparing two numpy arrays

In [2]:
import numpy as np

# comparing two arrays
a = np.array([2, 0, 0, 3])
b = np.array([2, 0, 2, 3])

c = a == b
print("a == b:", c)

c = a > b
print("a > b:", c)

c = a <= b
print("a <= b:", c)

a == b: [ True  True False  True]
a > b: [False False False False]
a <= b: [ True  True  True  True]


In [3]:
# check for boolean values inside arrays
c = a < b
print(np.any(c))
print(np.all(c))

True
False


In [4]:
# logical operations
print(a)
c = np.logical_and(a > 0, a < 4)
print("0 < a < 4:", c)

c = np.logical_or(a >= 0, a == 1)
print("a >= 0 or a == 1:", c)

c = np.logical_not(a)
print("not a:", c)

[2 0 0 3]
0 < a < 4: [ True False False  True]
a >= 0 or a == 1: [ True  True  True  True]
not a: [False  True  True False]


### b) Program using numpy array attributes like ndim, shape, size, and reshape() and flatten() methods# 

In [5]:
# numpy arrays of mixed types are not allowed
x = np.array([11, 11.2, 'adi', True])
print(type(x))
print(x)
print(x.dtype)

<class 'numpy.ndarray'>
['11' '11.2' 'adi' 'True']
<U32


In [9]:
# slicing
a = np.arange(2, 23)
print(a)

b = a[1:8:2]
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
[3 5 7 9]


In [10]:
b = a[::]
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [11]:
b = a[-2:2:-1]
print(b)

[21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5]


In [12]:
# indexing
print("a:", a)
print("a[0]: ", a[0])
print("a[4]: ", a[4])
print("a[-1]: ", a[-1])
print("a[-3]: ", a[-3])

a: [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
a[0]:  2
a[4]:  6
a[-1]:  22
a[-3]:  20


In [13]:
# array dimensions
a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4]])
c = np.array([[1, 2], [7, 8], [3, 4], [9, 11]])

print("a: ", a)
print("b: ", b)
print("c: ", c)

a:  [1 2 3 4]
b:  [[1 2]
 [3 4]]
c:  [[ 1  2]
 [ 7  8]
 [ 3  4]
 [ 9 11]]


In [14]:
# ndim
# ndim denotes the rank of the array (e.g. 1D array, 2D array)

print("a.ndim: ", a.ndim)
print("b.ndim: ", b.ndim)
print("c.ndim: ", c.ndim)

a.ndim:  1
b.ndim:  2
c.ndim:  2


In [15]:
# shape
# shape denotes number of elements along each dimension

print("a.shape: ", a.shape)
print("b.shape: ", b.shape)
print("c.shape: ", c.shape)

a.shape:  (4,)
b.shape:  (2, 2)
c.shape:  (4, 2)


In [16]:
# size
# size denotes the total number of elements in an array

print("a.size: ", a.size)
print("b.size: ", b.size)
print("c.size: ", c.size)

a.size:  4
b.size:  4
c.size:  8


In [17]:
# dtype

print("a.dtype", a.dtype)

d = np.array([2.3, 1, 5.6])
print(d)
print(d.dtype)

a.dtype int32
[2.3 1.  5.6]
float64


In [18]:
# reshape() method
arr1 = np.arange(10)
print(arr1)

arr1 = arr1.reshape(2, 5)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
arr2 = arr1.reshape(5, 2)
print(arr2)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
try:
    arr2 = arr1.reshape(5, 3)
except ValueError as e:
    print(e)

cannot reshape array of size 10 into shape (5,3)


In [21]:
# flatten() method
print(arr2)

arr3 = arr2.flatten()
print(arr3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [22]:
# sorting
# descending order
sorted_arr3 = np.sort(arr3)[::-1]
print(sorted_arr3)
#ascending order
print(np.sort(sorted_arr3))

[9 8 7 6 5 4 3 2 1 0]
[0 1 2 3 4 5 6 7 8 9]


### c) Program to perform arithmetic operations (addition, subtraction, multiplication, division) on numpy arrays# 

In [24]:
# numpy arrays
a = np.arange(10)
b = np.arange(2, 22, 2)

print("a:", a)
print("b:", b)

a: [0 1 2 3 4 5 6 7 8 9]
b: [ 2  4  6  8 10 12 14 16 18 20]


In [25]:
c = a + b
print(c)

[ 2  5  8 11 14 17 20 23 26 29]


In [26]:
print(a - b)

[ -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]


In [27]:
print(a / b)

[0.         0.25       0.33333333 0.375      0.4        0.41666667
 0.42857143 0.4375     0.44444444 0.45      ]


In [28]:
print(a * b)

[  0   4  12  24  40  60  84 112 144 180]


In [31]:
# 2D arrays
m1 = np.array([[4,9],[16,25]])
m2 = np.array([[36,49],[64,81]])

print("m1:", m1)
print("m2:", m2)

m1: [[ 4  9]
 [16 25]]
m2: [[36 49]
 [64 81]]


In [32]:
print(m1 + m2)

[[ 40  58]
 [ 80 106]]


In [33]:
print(m1 - m2)

[[-32 -40]
 [-48 -56]]


In [34]:
print(m1 / m2)

[[0.11111111 0.18367347]
 [0.25       0.30864198]]


In [35]:
print(m1 * m2)

[[ 144  441]
 [1024 2025]]
